# Generated by Django 2.1.3 on 2020-04-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_code',
            field=models.CharField(default='12345687', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
