# Generated by Django 2.2 on 2020-09-07 16:20

from django.db import migrations, models
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200830_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='通知内容'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='通知发布日期'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200, verbose_name='通知标题'),
        ),
    ]
