# Generated by Django 3.0 on 2021-02-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200907_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_code',
            field=models.CharField(max_length=9, verbose_name='注册码'),
        ),
    ]
