# Generated by Django 2.1.3 on 2020-08-30 14:30

from django.db import migrations, models
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='category',
            field=models.CharField(choices=[('film', '电影'), ('book', '书籍')], max_length=32, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='观看感想'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='title',
            field=models.CharField(max_length=128, verbose_name='标题'),
        ),
    ]
