# Generated by Django 3.0 on 2021-02-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_auto_20200830_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checklist',
            new_name='Watchlist',
        ),
    ]
