# Generated by Django 2.1.3 on 2020-04-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20200421_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
    ]
