# Generated by Django 2.1.3 on 2020-08-30 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20200421_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_name',
            field=models.CharField(max_length=128, verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传日期'),
        ),
    ]
