# Generated by Django 2.1.3 on 2019-11-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='content',
            field=models.TextField(default=' ', max_length=200),
        ),
    ]
