# Generated by Django 2.1.3 on 2019-11-16 21:50

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_notice_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
