# Generated by Django 2.1.3 on 2020-04-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200420_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='title',
        ),
        migrations.AddField(
            model_name='notice',
            name='caption',
            field=models.CharField(default='caption', max_length=100),
            preserve_default=False,
        ),
    ]
