# Generated by Django 2.1.3 on 2020-08-30 14:30

from django.db import migrations, models
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200502_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='caption',
            field=models.CharField(max_length=100, verbose_name='通知标题'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='通知内容'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='通知发布日期'),
        ),
    ]
