# Generated by Django 2.2 on 2020-09-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200830_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
