# Generated by Django 3.0 on 2021-02-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_article_mod_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.CharField(choices=[('draft', '草稿'), ('pub', '发布')], default='draft', max_length=8, verbose_name='状态'),
        ),
    ]
