# Generated by Django 2.1.3 on 2019-11-28 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
