# Generated by Django 2.1.3 on 2020-05-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_file_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='downloads_count',
            field=models.IntegerField(default=0, verbose_name='下载数'),
        ),
    ]
