# Generated by Django 3.0 on 2021-02-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200830_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
