# Generated by Django 3.0 on 2021-02-20 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, verbose_name='文件名')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传日期')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='下载数')),
            ],
        ),
    ]
