# Generated by Django 2.1.3 on 2019-11-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageboard',
            old_name='sub_data',
            new_name='sub_date',
        ),
    ]
