# Generated by Django 2.1.3 on 2019-11-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20191130_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageBoard',
        ),
    ]
