# Generated by Django 2.1.3 on 2020-05-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_userip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='serial_number',
            field=models.CharField(default=0, max_length=10, verbose_name='访问序号'),
        ),
    ]
