# Generated by Django 2.1.3 on 2020-06-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_userip_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='ip_attribution',
            field=models.CharField(default='', max_length=8, verbose_name='ip地址'),
        ),
    ]
