# Generated by Django 2.1.3 on 2020-08-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_userip_ip_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='ip_attribution',
            field=models.CharField(default='', max_length=64, verbose_name='ip地址'),
        ),
    ]
