# Generated by Django 2.2 on 2020-10-17 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20200830_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='EverydayVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='日期')),
                ('visits', models.IntegerField(default=0, verbose_name='访问量')),
            ],
        ),
    ]
