# Generated by Django 3.0 on 2021-02-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_aboutsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='everydayvisit',
            name='ip_attribution',
            field=models.CharField(default='', max_length=64, verbose_name='ip地址'),
        ),
    ]
