# Generated by Django 3.0 on 2021-02-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_everydayvisit_ip_attribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='everydayvisit',
            name='ip_attribution',
        ),
    ]
