# Generated by Django 2.1.3 on 2019-11-30 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1024)),
                ('sub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply', models.TextField(max_length=1024)),
            ],
        ),
    ]
