# Generated by Django 2.1.3 on 2019-11-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='reply',
            field=models.TextField(default='暂未回复', max_length=1024),
        ),
    ]
