# Generated by Django 2.1.3 on 2020-04-22 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0003_auto_20200422_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='reply_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
