# Generated by Django 2.1.3 on 2020-08-30 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0004_messageboard_reply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='content',
            field=models.TextField(max_length=1024, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='reply',
            field=models.TextField(default='暂未回复', max_length=1024, verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='reply_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='回复日期'),
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='sub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
    ]
