# Generated by Django 3.2.3 on 2021-07-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0005_auto_20200830_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='username',
            field=models.TextField(default='', max_length=16, verbose_name='匿名'),
        ),
    ]
