# Generated by Django 3.2.3 on 2021-09-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0006_messageboard_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='username',
            field=models.CharField(default='', max_length=16, verbose_name='匿名'),
        ),
    ]
